name: reusable deploy
on: 
    workflow_call:
        inputs:
            artifact-name: 
                description: The artifact to deploy
                required: false
                default: dist
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/download-artifact@v3
              with:
                  name: ${{ inputs.artifact-name }}
            - name: list file
              run: ls -l
            - name: output information
              run: echo "Deploying..."
